# Copyright (c) 2024-2024 Kevin Nguyen

# Project information
site_name: P-KISS-SBC
site_description: >-
  Simple, high performance, robust and reliable SIP Border Controller (SBC)
site_url: https://localhost.com
site_author: Kevin Nguyen

# Repository
repo_name: sccvn/pyfreebilling
repo_url: https://github.com/sccvn/pyfreebilling
edit_uri: ''

# Copyright
copyright: >
  Copyright &copy; 2024 - 2024 Kevin Nguyen -- 
  <a href="#__consent">Change cookie settings</a>

# Configuration
theme:
  name: material
  custom_dir: docs/theme_overrides
  features:
    - navigation.footer
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - toc.follow
    - search.highlight
    - search.share
    - search.suggest
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      toggle:
        icon: material/weather-sunny 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  font:
    text: Open Sans
    code: Open Sans Mono
  icon:
    repo: fontawesome/brands/git-alt
  language: en

extra:
  alternate:
    - name: English
      link: /en/ 
      lang: en
    - name: French
      link: /fr/
      lang: fr
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/sccvn
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/r/sccvn
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.

# Extensions
markdown_extensions:
- abbr
- admonition
- attr_list
- def_list
- footnotes
- md_in_html
- pymdownx.betterem:
    smart_enable: all
- pymdownx.details
- pymdownx.emoji:
    emoji_generator: !!python/name:material.extensions.emoji.to_svg
    emoji_index: !!python/name:material.extensions.emoji.twemoji
- pymdownx.highlight:
    anchor_linenums: true
    line_spans: __span
    pygments_lang_class: true
- pymdownx.inlinehilite
- pymdownx.smartsymbols
- pymdownx.superfences
- toc:
    permalink: true

# Plugins
plugins:
  - search
  - minify:
      minify_html: true
  #- privacy
  - social
  - i18n:
      docs_structure: suffix
      default_language: en
      default_language_only: false
      docs_structure: suffix
      languages:
        en: '<img style="height: 10px; border: 0px;" alt="en" class="twemoji" src="https://twemoji.maxcdn.com/v/latest/svg/1f1ec-1f1e7.svg" title="english" /> English'
        fr: '<img style="height: 10px; border: 0px;" alt="fr" class="twemoji" src="https://twemoji.maxcdn.com/v/latest/svg/1f1eb-1f1f7.svg" title="français" /> Français'
      nav_translations:
        fr:
          Welcome: Bienvenue
          Philosophy: Philosophie
          Differences between PyFreeBilling and PKS: Différences entre PyFreeBilling et PKS
          Does PKS perform LCR: Est-ce que PKS fait du LCR
          Use Cases: Cas d'Utilisation
          Getting Started: Démarrage rapide
          User Guide: Guide Utilisateur
          How To: Comment Faire
          How to Upgrade: Comment Mettre à Jour
          Backup and Recovery: Sauvegarde et Restauration
          Troubleshooting: Résolution de Problèmes
          Requirements: Prérequis
          Best Practices: Bonnes Pratiques
          Contributing: Contribuer
          Release Notes: Notes de Mise à Jour
          Manage: Administrer
  - git-revision-date-localized:
      enable_creation_date: false
      fallback_to_build_date: true
      type: iso_date
  - git-authors
  - rss:
      match_path: .* 
      date_from_meta:
        as_creation: date
      categories:
        - categories
        - tags

# Page tree
nav:
  - Home:
    - Introduction: index.md
    - Philosophy: philosophy.md
    - Best Practices: bestpractices.md
    - FAQs:
      - Index: faq/index.md
      - Differences between PyFreeBilling and PKS: faq/pyfreebilling-pks-differences.md
      - Does PKS perform LCR: faq/lcr-routing.md
    - License: license.md
  - Use Cases: 
    - Introduction: use-cases/usecases.md
    - Securing VoIP system: use-cases/securing-telephony-system.md
    - Failover: use-cases/failover.md
    - High Availability: use-cases/ipbx-high-availability.md
    - Geo routing: use-cases/geographical-distribution-ipbx.md
    - Connect Multitenant IPBX: use-cases/connecting-mutitenant-ipbx-to-carrier.md
    - Multiple Carriers: use-cases/connecting-ipbx-to-multiple-carriers.md
  - Getting Started: 
    - getting-started.md
    - Requirements: user-guide/requirements.md
    - Installation: user-guide/installation.md
    - Post Install: user-guide/configuration.md
    - Manage: user-guide/manage.md
  - How To:
    - Backup and Recovery: how-to/backup-recovery.md
    - How to Upgrade: how-to/upgrade.md
    - Troubleshooting: how-to/troubleshooting.md 
  - Contributing:
    - contributing/index.md
    - Reporting a bug: contributing/reporting-a-bug.md
    - Reporting a docs issue: contributing/reporting-a-docs-issue.md
    - Requesting a change: contributing/requesting-a-change.md
    - Asking a question: https://github.com/sccvn/pyfreebilling/discussions
  - Release Notes: changelog/index.md
