version: "3.8"

services:
  pks-sip:
    depends_on:
      - pks-redis
      - pks-rtp
      - pks-fs-1
      - pks_mysql
    environment:
      DB_URL: "mysql://root:mypass@pks-mysql/pks"
  
  pks-mysql:
    container_name: pks-mysql
    hostname: mysql.pks.local
<<<<<<< HEAD
    image: mysql:8.0-debian
=======
    image: mysql:7.0
>>>>>>> c1b746d... update dev with new build rtpengine from submodule in plugins
    cap_add:
      - SYS_NICE
    restart: unless-stopped
    volumes:
      - pks-mysql-data:/var/lib/mysql
      - ./db/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment: 
      MYSQL_ROOT_PASSWORD: mypass
      MYSQL_DATABASE: pks
    networks:
      main:
        aliases:
          - pks-mysql

networks:
  main:

volumes:
  pks-mysql-data: