version: "3.8"
include:
  - path:
      - docker-compose.mysql.yml
      - docker-compose.postgres.yml
services:
  pks-sip:
    container_name: pks-sip
    hostname: sip.pks.local
    image: fgst/pks-sipproxy:4.0.0beta02
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - pks-sip-cfg:/etc/kamailio:rw
      # - ./tests/db-test:/etc/kamailio/db:ro
      - pks-db-data:/etc/kamailio/db:ro
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    environment:
      ENVIRONMENT: ${ENVIRONMENT:-dev}
      LISTEN_ADVERTISE: ${LISTEN_ADVERTISE:-apac.belltouch.xyz}
      KAMAILIO_LOG_LEVEL: ${KAMAILIO_LOG_LEVEL:-info}
      RTPENGINE_URL: ${RTPENGINE_URL:-rtp.pks.local}
      REDIS_URL: ${REDIS_URL:-redis.pks.local}
      ALIAS: ${ALIAS:-sip.pks.local}
      DB: ${DB}
      DB_URL: ${DB_URL:-mysql://root:mypass@127.0.0.1/pks}
      DB_MYSQL: ${DB_MYSQL:-127.0.0.1}
      DB_SQLITE: ${DB_SQLITE}
      DB_PGSQL: ${DB_PGSQL}
      LOCAL_IP: ${LOCAL_IP:-42.116.255.41}
      SIP_DOMAIN_KEEPALIVE: ${SIP_DOMAIN_KEEPALIVE:-proxy@pks}
      NOT_PROBING: ${NOT_PROBING}
      NOT_SANDBOX: ${NOT_SANDBOX:-SANDBOX}
    depends_on:
      - pks-redis
      - pks-rtp
      - pks-mysql
    #ports:
    #  - "5060:5060/udp"
    #  - "5070:5070/udp"
    network_mode: host

  pks-redis:
    container_name: pks-redis
    hostname: redis.pks.local
    image: redis:7-alpine
    restart: unless-stopped
    expose:
      - '6379'
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    network_mode: host
    volumes:
      - pks-redis-data:/data

  pks-rtp:
    container_name: pks-rtp
    hostname: rtp.pks.local
    image: fgst/pks-rtpengine:v1.0.1
    restart: unless-stopped
    privileged: true
    expose:
      - "22222/udp"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    environment:
      BIND_NG_PORT: ${BIND_NG_PORT:-22222}
      PUBLIC_IP: ${PUBLIC_IP}
      LOCAL_IP: ${LOCAL_IP}
      INTERNAL_IP: ${INTERNAL_IP}
      PORT_MIN: ${PORT_MIN:-16000}
      PORT_MAX: ${PORT_MAX:-18000}
      LOG_LEVEL: ${LOG_LEVEL:-6}
    network_mode: host

networks:
  main:

volumes:
  pks-sip-cfg:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: $HOME/srv/pks/kamailio
  pks-redis-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: $HOME/srv/pks/redis
  pks-db-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: $HOME/srv/pks/db
  pks-mysql-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: $HOME/srv/pks/mysql
  pks-pgsql-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: $HOME/srv/pks/pgsql