services:  
  # pks-sip:
  #   depends_on:
  #     - pks-redis
  #     - pks-rtp
  #     - pks-fs-1
  #     - pks_postgres
  #   environment:
  #     - DB_URL: postgres://postgres:mypass@pks-postgres/pks
  
  pks-pgsql:
    container_name: pks-postgres
    hostname: postgres.pks.local
    image: postgres
    restart: unless-stopped
    volumes:
      - pks-pgsql-data:/var/lib/postgresql/data
      - ./db/postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mypass
    networks:
      main:
        aliases:
          - pks-postgres